version: '3'

services:
  dev:
    image: node:16-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.output
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    working_dir: /app
    command: sh -c "yarn && yarn serve"
